In [2]:
# Importar módulos necesarios
import pandas as pd
import seaborn as sns
import plotly.express as px

# Configurar Pandas para mostrar todas las filas y columnas
pd.set_option('display.max_rows', None)  # Muestra todas las filas
pd.set_option('display.max_columns', None)  # Muestra todas las columnas

Seaborn viene con datasets predeterminados, disponibles para utilizar en la librería. Los mismos se encuentran cargados en este enlace de github:

- https://github.com/mwaskom/seaborn-data

Trayendo y probando los datasets `iris` y `penguins`.

In [3]:
iris= sns.load_dataset("iris")
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
penguins = sns.load_dataset('penguins')
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

Función y Programa Principal

In [5]:
def plot_interactive_graphs():
    dataset = input('¿Qué conjunto de datos desea utilizar? (Iris/Penguins): ').strip().lower()

    if dataset == 'iris':
        iris = sns.load_dataset('iris')
        # 1. Gráfico de Barras (barh): Muentras la longitud del sépalo por especie y el promedio entre ellas.
        average_sepal_length_by_species = iris.groupby('species')['sepal_length'].mean().reset_index()
        average_sepal_length = iris['sepal_length'].mean()
        fig = px.bar(
            average_sepal_length_by_species,
            x='species',
            y='sepal_length',
            title='Longitud Promedio del Sépalo por Especie',
            labels={'sepal_length': 'Longitud del Sépalo (cm)', 'species': 'Especies'}
        )
        fig.add_hline(
            y=average_sepal_length,
            line_color='red',
            line_width=3,
            line_dash='dash',
            annotation_text=f'Promedio: {average_sepal_length:.2f}',
            annotation_font=dict(
                size=16,
                color='red',
            )
        )
        fig.show()
        # 2. Gráfico Circular (Pie): Muestra la proporción por especie.
        fig2 = px.pie(iris, names='species', title='Distribución de Especies de Iris')
        fig2.show()
        # 3. Gráfico de Bigotes (Boxplot): Muestra la distribución de la anchura del sépalo según la especie.
        fig3 = px.box(
            iris,
            x='species',
            y='petal_width',
            title='Distribución de la Anchura del Sépalo por Especie',
            labels={'petal_width': 'Anchura del Sépalo (cm)', 'species': 'Especies'}
        )
        fig3.show()

    elif dataset == 'penguins':
        penguins = sns.load_dataset('penguins')
        # 1. Gráfico de Barras (barh): Muestra la longitud de las aletas por especie y el promedio entre ellas.
        average_flipper_length_species = penguins.groupby('species')['flipper_length_mm'].mean().reset_index()
        average_flipper_length = penguins['flipper_length_mm'].mean()
        fig = px.bar(
            average_flipper_length_species,
            x='species',
            y='flipper_length_mm',
            title='Longitud Promedio de la Aleta Según la Especie',
            labels={'flipper_length_mm': 'Longitud promedio de la aleta (cm)', 'species': 'Especies'}
        )
        fig.add_hline(
            y=average_flipper_length,
            line_color='red',
            line_width=3,
            line_dash='dash',
            annotation_text=f'Promedio general entre especies: {average_flipper_length:.2f}',
            annotation_font=dict(
                size=16,
                color='red',
            )
        )
        fig.show()
        # # 2. Gráfico Circular (Pie): Muestra la proporción por especie.
        fig2 = px.pie(penguins, names='species', title='Distribución de Especies de Penguins')
        fig2.show()
        # 3. Gráfico de Bigotes (Boxplot): Muestra la distribución de la profundidad del pico según la especie.
        fig3 = px.box(
            penguins,
            x='species',
            y='bill_depth_mm',
            title='Distribución de la Profundidad del Pico Según la Especie',
            labels={'bill_depth_mm': 'Profundidad del Pico (mm)', 'species': 'Especies'}
        )
        fig3.show()

    else:
        print('Opción incorrecta. Reanude la ejecución e ingrese los nombres correctos.')

In [7]:
# Programa Principal
plot_interactive_graphs()

¿Qué conjunto de datos desea utilizar? (Iris/Penguins): Penguins